# ====================== Header ======================
# fileName       : application-local.yaml
# author         : 우태균
# description    : 로컬 개발 환경용 properties 파일
# ====================================================

spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: create
    generate-ddl: true
    database: h2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: kr.pe.rannect.api.utils.jpa.UpperCaseNamingStrategy
    defer-datasource-initialization: true # data-h2.sql
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:~/rannect
    driverClassName: org.h2.Driver
    username: sa
    password:
  # Embedded Redis
  redis:
    host: localhost
    port: 6379
    redis-m1-location: binary/redis-server-6.2.5-mac-arm64
  # data-h2.sql
  sql:
    init:
      mode: always
      encoding: UTF-8
      data-locations: classpath:data-h2.sql

# Hibernate Logging
logging:
  level:
    org:
      hibernate: info