# ====================== Header ======================
# author         : 우태균
# description    : 기본 profile 파일
# ====================================================

# swagger
springdoc:
  packages-to-scan: kr.pe.rannect.api.controller
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

spring:
  # JPA
  jpa:
    open-in-view: false
  # Off ResourceHttpRequestHandler
  web:
    resources:
      add-mappings: false
  config:
    import: auth-secret.yaml