# ====================== Header ======================
# fileName       : application-local.yaml
# author         : 우태균
# description    : 로컬 개발 환경용 properties 파일
# ====================================================

spring:
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: create
    generate-ddl: true
    database: h2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      naming:
        physical-strategy: kr.pe.rannect.api.utils.jpa.UpperCaseNamingStrategy
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:~/rannect
    driverClassName: org.h2.Driver
    username: sa
    password:

# Hibernate Logging
logging:
  level:
    org:
      hibernate: info